### PR TITLE
A fixed-navbar-top theme option for the primary-menu.

### PR DESCRIPTION
**Pull request by Blinden**
Hello Konstantin,

I have implemented a fixed-navbar-top for the primary-menu. 
I just added it to header.php and haven't touched the rest of header.php.
You can switch it on/off in the theme options (current default is on).

Let me know if you like it...

Bart.

### CODE REVIEW

**Comment by Blinden** [comment]
After my first commit I noticed a vertical-scrollbar that sometimes appears if you play with the screen size. 
The reason is the page and the row class combination in line 65 of header.php. 
I moved the page class to the container and then started to clean up the css.

**Comment by obenland** [comment]
This entire vertical scroll bar thing is very annoying.
I had it fixed like five times already, but it keeps coming back.

While I like your approach here, I do want to try to stick with Bootstrap's default styling and shave that 5px margin of the 768px-view somehow. Just: how? :)

**Comment by Blinden** [comment]
I agree. Ideal would be no patching of bootstrap in style.css.

Which 5px margin do you mean? 

I'm experimenting with adding an extra containing div for #page....

**Comment by obenland** [comment]
The 5px in margin-right on #page that cause the vertical scrollbar.

(Temporarily?) fixed it with a494bcd80636efae9c612d636f64cd5a4126a3bf

**Pull request closed without merging**
