### PR TITLE
Updated CSS to fix margins

### PR DESCRIPTION
**Pull request by Blinden**
Hello Konstantin,

As promised my attempt to fix the css.

I moved #page from .row to the parent .container in header.php and gave #page some paddings and margins. 
And that was it really. All elements align and behave themeselves.

Child-themes can even adjust the padding easily.

Let me know what you think,

Bart.

### CODE REVIEW

**Comment by obenland** [comment]
Do you have a demo page with this fixes running somewhere?
With v2.0.4 on the brink of release, shouldn't we wait and see how this might play into it?

**Comment by Blinden** [comment]
1. I will try to launch one to day. When it's up I will let you know.
2. They have a bootstrap2.0.4-wip branch (work in progress). Maybe I (we) can test against that. You have to compile it though and so far I haven't done that. But that's something I wanted to try anyhow so... 
   Might even be a great extension to the the-bootstrap admin suite.

**Comment by Blinden** [comment]
It's up and running on http://oo-it.nl/the-bootstrap

**Comment by obenland** [comment]
I'll close it as wontfix for now. Retested the existing markup with Bootstrap 2.1 and I couldn't find too much wrong with it.

Please feel free to open further pull requests when you discover possibilities for vast improvements on this!

Thanks,
Konstantin

**Pull request closed without merging**
