### PR TITLE
update dutch language files, added html conditional classes

### PR DESCRIPTION
**Pull request by m038**
Hey,

I've updated the Dutch translation a bit, since there were some spelling mistakes and inconsistencies between translations. I've also changed all forms of addressing the user to the polite form of addressing a user. Would be more consistent and professional i think.

Further i've added the HTML5Boilerplate html-tag conditional classes to your file. I think it makes changing the layout for other browsers or fixing specific browser bugs easier. There are some problems in IE8 and IE9 also has a render error with border-radius and gradients applied on the same element.

Hope it helps!

Greets m038

### CODE REVIEW

**Comment by m038** [comment]
BTW would you prefer me to work in another branch if i update the translation files?

**Comment by obenland** [comment]
Hi Mischa,

thank you for your continued contribution!

It doesn't really matter which branch you submit your pull requests against, since I always checkout a new branch with the changes, (fix them up if necessary) and merge them later into the appropriate one.

Concerning the IE conditionals: Bootstrap generally has IE stuff built in and does not rely on those kind of selectors. If devs really would build upon them, they'd hopefully do that in a Child Theme and then they could implement them in the Child Theme's  `header.php`. Would you agree?

Thanks again for your time and effort!

**Comment by obenland** [comment]
And it's in: https://github.com/obenland/the-bootstrap/commit/d285df4ce01d2d012d5ea04114f72e5379ff4cb0

**Comment by m038** [comment]
Hi Konstantin,

I'm not that familiar with bootstrap yet, my colleague encouraged me to look further into it. So i'm sorry if  created a duplicate functionality with the html conditional classes. Please forget about it and ignore it. :)

Offcourse you're welcome. If i find any other bugs in my translation you'll get the msg :)

Mischa

**Pull request closed without merging**
